
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Estudiante
 */
public class Main extends javax.swing.JFrame {

    ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("carro1.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("carro2.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon3 = new ImageIcon(new ImageIcon("carro3.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon4 = new ImageIcon(new ImageIcon("carro4.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon5 = new ImageIcon(new ImageIcon("carro5.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon6 = new ImageIcon(new ImageIcon("carro6.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon7 = new ImageIcon(new ImageIcon("carro7.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon8 = new ImageIcon(new ImageIcon("carro8.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    ImageIcon imageIcon9 = new ImageIcon(new ImageIcon("carro9.png").getImage().getScaledInstance(173, 62, Image.SCALE_DEFAULT));
    
    
    public Main() {
        initComponents();
        avanzarCarro1();
    }
    
    public void avanzarCarro1(){
        int x1 = jLabel1.getLocation().x;
        int x=0;
        int y = jLabel1.getY();
        System.out.println(x1);
        while (x<200){
            jLabel1.setBounds(x1+x, y, 173, 62);
            x++;
            System.out.println(x);
        }
        System.out.println(jLabel1.getX());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(imageIcon1);
        jLabel1.setText("a");

        jLabel2.setIcon(imageIcon2);

        jLabel3.setIcon(imageIcon3);

        jLabel4.setIcon(imageIcon4);

        jLabel5.setIcon(imageIcon5);

        jLabel6.setIcon(imageIcon6);

        jLabel7.setIcon(imageIcon7);

        jLabel8.setIcon(imageIcon8);

        jLabel9.setIcon(imageIcon9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(584, 920, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
